version: '3'

services:
  app:
    restart: unless-stopped
    container_name: docuchain-frontend-app
    image: docuchain-frontend:latest
    entrypoint: ["yarn", "start"]
    env_file: .env
    ports:
      - "3000:3000"
  local-nginx:
      container_name: local-nginx
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - "4000:4000"
      depends_on:
        - app
        