FROM node:18-alpine

WORKDIR /usr/src/app

COPY . .

ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG NEXT_PUBLIC_API_URL

ENV NODE_ENV=staging
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

RUN yarn install --network-timeout 600000

RUN echo "ENV: ${NODE_ENV}" && yarn build

EXPOSE 3000
