export { default as IconSearch } from 'src/icons/inline/search.inline.svg'
export { default as IconPlus } from 'src/icons/inline/plus.inline.svg'
export { default as IconArrowDown } from 'src/icons/inline/arrow-down.inline.svg'
export { default as IconArrowDownLong } from 'src/icons/inline/arrow-down-long.inline.svg'
export { default as IconArrowRight } from 'src/icons/inline/arrow-right.inline.svg'
export { default as IconArrowRightLight } from 'src/icons/inline/arrow-right-light.inline.svg'
export { default as IconArrows } from 'src/icons/inline/arrows.inline.svg'
export { default as IconCheck } from 'src/icons/inline/check.inline.svg'
export { default as IconClose } from 'src/icons/inline/close.inline.svg'
export { default as IconDots } from 'src/icons/inline/dots.inline.svg'
export { default as IconEdit } from 'src/icons/inline/edit.inline.svg'
export { default as IconEye } from 'src/icons/inline/eye.inline.svg'
export { default as IconFile } from 'src/icons/inline/file.inline.svg'
export { default as IconUser } from 'src/icons/inline/person.inline.svg'
export { default as IconPlusBlack } from 'src/icons/inline/plus-black.inline.svg'
export { default as IconRefresh } from 'src/icons/inline/refresh.inline.svg'
export { default as IconStar } from 'src/icons/inline/star.inline.svg'
export { default as IconStepActive } from 'src/icons/inline/step-active.inline.svg'
export { default as IconStepNext } from 'src/icons/inline/step-next.inline.svg'
export { default as IconStepCheck } from 'src/icons/inline/step-check.inline.svg'
export { default as IconUsers } from 'src/icons/inline/users.inline.svg'
export { default as IconMinus } from 'src/icons/inline/minus.inline.svg'
export { default as IconCheckDot } from 'src/icons/inline/check-dot.inline.svg'

export { default as IconUpload } from 'src/icons/inline/upload-cloud.inline.svg'

export { default as IconXLogo } from 'src/icons/socials/x.inline.svg'
export { default as IconLinkedinLogo } from 'src/icons/socials/in.inline.svg'
export { default as IconInstagramLogo } from 'src/icons/socials/instagram.inline.svg'
export { default as IconFacebookLogo } from 'src/icons/socials/facebook.inline.svg'
export { default as IconTelegramLogo } from 'src/icons/socials/tg.inline.svg'

export { default as IconPDF } from 'src/icons/docs/pdf.inline.svg'
export { default as IconDOC } from 'src/icons/docs/doc.inline.svg'
export { default as IconDOCX } from 'src/icons/docs/docx.inline.svg'
export { default as IconDocumentUpload } from 'src/icons/docs/upload-document.inline.svg'
export { default as IconDocumentSent } from 'src/icons/docs/document-sent.inline.svg'
export { default as IconDocumentSigned } from 'src/icons/docs/document-signed.inline.svg'
