---
- name: Deploy DocuChain frontend
  gather_facts: true
  hosts: localhost
  become: yes

  tasks:

    - name: Copy files to base dir
      copy:
        src: "../{{ item }}"
        dest: "/opt/app/frontend/"
      with_items:
        - "docker-compose.yml"
        - ".env"

    - name: Deploy docker-compose
      community.docker.docker_compose_v2:
        project_src: "/opt/app/frontend"
        build: always
        recreate: always
        remove_orphans: true
        env_files: 
          - "/opt/app/frontend/.env"
        files:
          - "{{ docuchain_frontend.compose_filename | default('/opt/app/frontend/docker-compose.yml') }}"
