name: Build and deploy Docuchain frontend

on:
  push:
    branches: [ "main", "cicd" ]

env:
  RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}

jobs:

  deploy:

    runs-on: [ "self-hosted", "prod" ]

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        
    - name: Build docker image
      run: make build-prod

    - name: Start application
      run: source /home/deployer/ansible/bin/activate && cd ansible && ansible-playbook deploy-frontend.yml -e ansible_user=deployer -b -v
